services:
  db:
    build: ./mysql
    healthcheck:
      interval: 10s
      retries: 5
      test:
      - CMD
      - mysqladmin
      - ping
      - -h
      - localhost
      - --password=idor_broken_authz_trading_platform
      - -u
      - root
      timeout: 1s
    image: xben-001-24-db
    ports: []
  idor_broken_authz_trading_platform:
    build:
      args:
      - FLAG
      context: ./app
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      interval: 10s
      retries: 5
      test:
      - CMD
      - curl
      - -f
      - http://localhost:80/
      timeout: 1s
    image: xben-001-24-idor_broken_authz_trading_platform
    ports:
    - 65273:80
