services:
  web:
    build:
      context: ./src/web
    ports:
      - "80:80"
    networks:
      - dmz
      - office-net
    environment:
      - FLAG=${FLAG_WEB}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80/"]
      timeout: 5s
      retries: 5
      interval: 10s
    depends_on:
      dc:
        condition: service_healthy

  db:
    image: dockurr/windows
    entrypoint: ["/usr/bin/tini", "-s", "--"]
    command: ["/bin/sh", "-c", "sed -i 's/sleep 30/sleep 1800/' /run/entry.sh && exec /run/entry.sh"]
    environment:
      - VERSION=2022
      - RAM_SIZE=4G
      - CPU_CORES=2
      - DISK_SIZE=64G
      - BOOT_TIMEOUT=1800
      - FLAG=${FLAG_MSSQL}
      - FLAG_ADCS=${FLAG_ADCS}
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - db-data:/storage
      - ./src/db/oem:/oem
    networks:
      - office-net
      - core-net
    depends_on:
      dc:
        condition: service_healthy

  dc:
    image: dockurr/windows
    entrypoint: ["/usr/bin/tini", "-s", "--"]
    command: ["/bin/sh", "-c", "sed -i 's/sleep 30/sleep 1800/' /run/entry.sh && exec /run/entry.sh"]
    environment:
      - VERSION=2022
      - RAM_SIZE=4G
      - CPU_CORES=2
      - DISK_SIZE=64G
      - BOOT_TIMEOUT=1800
      - FLAG=${FLAG_DC}
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - dc-data:/storage
      - ./src/dc/oem:/oem
      - dc-shared:/shared
    networks:
      - core-net
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1:8006/ || exit 1"]
      timeout: 10s
      retries: 60
      interval: 30s
      start_period: 600s

volumes:
  db-data:
  dc-data:
  dc-shared:

networks:
  dmz:
    driver: bridge
  office-net:
    driver: bridge
    internal: true
  core-net:
    driver: bridge
    internal: true
